<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DotnetAPI.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="DotnetAPI.Tests\**" />
    <Content Remove="DotnetAPI.Tests\**" />
    <EmbeddedResource Remove="DotnetAPI.Tests\**" />
    <None Remove="DotnetAPI.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="9.0.0" />
    <PackageReference Include="automapper" Version="13.0.1" />
    <PackageReference Include="dapper" Version="2.1.35" />

    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.8" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

</Project>
